apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- path: namespace_patch.json
  target:
    kind: Namespace
    name: kubeflow
    version: v1
resources:
- github.com/kubeflow/manifests/common/kubeflow-namespace/base?ref=42a19c0825d23149c0edb67757b04a635d6a26f0 #1.3.1
