apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: notebook-auth-policy-checker
rules:
- apiGroups:
    - 'kubeflow.org'
  resources:
    - 'notebooks'
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - security.istio.io
  resources:
    - 'authorizationpolicies'
  verbs:
    - get
    - list
    - watch
    - create
    - update
    - delete
- apiGroups:
    - ''
  resources:
    - 'events'
  verbs:
    - create
    - patch
