apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
    - github.com/kubeflow/manifests/contrib/seldon/seldon-core-operator/base?ref=48ea3f8ed74ae4d14520119a9f3d13c16fb80110 # tag=v1.3.1
