nameOverride: "minio-gateway"
commonLabels:
  app: minio-gateway
global:
  minio:
    existingSecret: minio-gateway-secret
gateway:
  enabled: false
  replicaCount: 1
  type: azure
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: "25%"
      maxUnavailable: "25%"
  # autoscaling:
  #   enabled: true
  #   minReplicas: "2"
  #   maxReplicas: "4"
  #   targetCPU: "60"
  #   targetMemory: "60"
  auth:
    azure:
      storageAccountNameExistingSecret: "azure-blob-storage"
      storageAccountNameExistingSecretKey: "storageAccountName"
      storageAccountKeyExistingSecret: "azure-blob-storage"
      storageAccountKeyExistingSecretKey: "storageAccountKey"
extraEnv:
  - name: MINIO_ETCD_ENDPOINTS
    value: http://minio-gateway-etcd:2379/
  - name: MINIO_IAM_OPA_URL
    value: http://minio-gateway-opa:8181/v1/data/httpapi/authz
extraVolumes:
- name: minio-sh
  emptyDir: {}
extraVolumeMounts:
- mountPath: /minio.sh
  subPath: minio.sh
  name: minio-sh
initContainers:
- name: wait-for-sidecar
  image: busybox
  command:
  - sh
  - -c
  - |
    echo '#!/bin/sh' > /custom/minio.sh
    echo 'sleep 15' >> /custom/minio.sh
    echo 'echo "Waiting for sidecar..."' >> /custom/minio.sh
    echo 'echo "Sidecar is ready."' >> /custom/minio.sh
    echo 'echo exec minio $@' >> /custom/minio.sh
    echo 'exec minio $@' >> /custom/minio.sh
    chmod 555 /custom/minio.sh
    chown nobody:nobody /custom/minio.sh
    echo "Wrote the minio.sh script to shared volume."
  volumeMounts:
  - mountPath: /custom
    name: minio-sh
# Modification here.
image:
  registry: docker.io #k8scc01covidacr.azurecr.io
  repository: bitnami/minio
  tag: 2021.5.27-debian-10-r8
  #6379f1af
  # registry: docker.io
  # repository: bitnami/minio
  # tag: 2021.5.27-debian-10-r8
# Wait for the istio proxy
command: ["sh", "/minio.sh"]
ingress:
  enabled: false
  hostname: storage-system.aaw.cloud.statcan.ca
resources:
  limits:
    cpu: "4"
    memory: 16Gi
  requests:
    cpu: "2"
    memory: 2Gi
# nodeSelector:
#   agentpool: storage
# affinity:
#   podAntiAffinity:
#     preferredDuringSchedulingIgnoredDuringExecution:
#     - podAffinityTerm:
#         labelSelector:
#           matchExpressions:
#           - key: app
#             operator: In
#             values:
#             - minio-gateway
#         topologyKey: kubernetes.io/hostname
#       weight: 100
tolerations: []
# - effect: NoSchedule
#   key: node.statcan.gc.ca/purpose
#   operator: Equal
#   value: system
# - effect: NoSchedule
#   key: node.statcan.gc.ca/use
#   operator: Equal
#   value: storage
# # - effect: NoSchedule
# #   key: data.statcan.gc.ca/classification
# #   operator: Equal
# #   value: protected-b
