apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: profiles-controller
  namespace: daaas-system
spec:
  project: platform
  destination:
    namespace: daaas-system
    name: in-cluster
  source:
    repoURL: 'https://statcan.github.io/charts'
    chart: profiles-controller
    targetRevision: 0.1.4
    helm:
      releaseName: profiles-controller
      values: |
        image:
          repository: k8scc01covidacr.azurecr.io/profiles-controller
          tag: b37908165f521882abc77126e81befcffdfd3853
        components:
          rbac:
            supportGroups:
              # DAaaS-AAW-Support
              - 468415c1-d3c2-4c7c-a69d-38f3ce11d351
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
