apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow

resources:
- github.com/kubeflow/manifests/common/user-namespace/base?ref=2f76822b03bbf539292d23ca1928a335950bdb9e #v1.3
