apiVersion: v1
kind: ServiceAccount
metadata:
  name: minio-credential-injector
  namespace: daaas-system
  labels:
    apps.kubernetes.io/name: minio-credential-injector
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-instances-json
data:
  instances.json: |
    {"name": "minio_standard_tenant_1", "classification": "unclassified", "serviceUrl": "http://minio.minio-legacy-system:80"}
    {"name": "minio_premium_tenant_1", "classification": "unclassified", "serviceUrl": "http://minio.minio-premium-legacy-system:80"}
---
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: minio-credential-injector-issuer
  namespace: daaas-system
  labels:
    apps.kubernetes.io/name: minio-credential-injector
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: minio-credential-injector
  namespace: daaas-system
  labels:
    apps.kubernetes.io/name: minio-credential-injector
spec:
  secretName: minio-credential-injector-tls
  commonName: "minio-credential-injector.daaas-system.svc.cluster.local"
  dnsNames:
  - minio-credential-injector
  - minio-credential-injector.daaas-system
  - minio-credential-injector.daaas-system.svc
  - minio-credential-injector.daaas-system.svc.cluster
  isCA: true
  duration: 8760h0m0s
  issuerRef:
    name: minio-credential-injector-issuer
    kind: Issuer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-credential-injector
  namespace: daaas-system
  labels:
    apps.kubernetes.io/name: minio-credential-injector
spec:
  replicas: 3
  selector:
    matchLabels:
      apps.kubernetes.io/name: minio-credential-injector
  template:
    metadata:
      labels:
        apps.kubernetes.io/name: minio-credential-injector
      annotations:
        sidecar.istio.io/inject: 'false'
    spec:
      serviceAccountName: minio-credential-injector
      imagePullSecrets:
        - name: k8scc01covidacr-registry-connection
      containers:
      - name: minio-credential-injector
        image: k8scc01covidacr.azurecr.io/minio-credential-injector:2bb5e5eb51159a61d05ed821c21b8c21c48a4b4d
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: https
          containerPort: 8443
        volumeMounts:
        - name: certs
          mountPath: /certs
          readOnly: true
        - name: instances
          mountPath: /instances.json
          subPath: instances.json
          readOnly: true
      volumes:
      - name: certs
        secret:
          secretName: minio-credential-injector-tls
      - name: instances
        configMap:
          name: minio-instances-json
---
apiVersion: v1
kind: Service
metadata:
  name: minio-credential-injector
  namespace: daaas-system
  labels:
    apps.kubernetes.io/name: minio-credential-injector
spec:
  selector:
    apps.kubernetes.io/name: minio-credential-injector
  ports:
  - name: https
    port: 443
    targetPort: 8443
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: daaas-system/minio-credential-injector
  labels:
    apps.kubernetes.io/name: minio-credential-injector
  name: minio-credential-injector
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: minio-credential-injector
      namespace: daaas-system
      path: /mutate
      port: 443
  failurePolicy: Ignore
  name: minio-credential-injector.statcan.gc.ca
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
    scope: '*'
