apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/kubeflow/katib/manifests/v1beta1/installs/katib-with-kubeflow?ref=152ec0797c3025d6e4465df0f0654bf3b705fa18 #tag v0.12.0
